import type { Metadata } from "next";
import "./globals.css";
import { Urbanist } from "next/font/google";
import { ParticleConnectkit } from "@/components/Connectkit";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-urbanist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} text-white antialiased`}>
        <ParticleConnectkit>{children}</ParticleConnectkit>
      </body>
    </html>
  );
}
