import type { Metadata } from "next";
import "./globals.css";
import { Urbanist, Poppins } from "next/font/google";
import { ParticleConnectkit } from "@/components/Connectkit";
import { Toaster } from "sonner";
import ClientWrapper from "@/components/ClientWrapper";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-urbanist",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${poppins.variable} text-white antialiased`}
      >
        <Toaster richColors />
        <ParticleConnectkit>
          <ClientWrapper>{children}</ClientWrapper>
        </ParticleConnectkit>
      </body>
    </html>
  );
}
